# Generated by Django 5.2 on 2025-05-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0003_shortcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='short',
            old_name='creater_at',
            new_name='created_at',
        ),
    ]
